---
- name: Clone the GitHub repository
  git:
    repo: 'https://github.com/manishkulkarni2003/first-devops-project.git'
    dest: /home/{{ ansible_user }}/first-devops-project
    version: main
    force: yes

- name: Run Docker Compose
  shell: |
    cd /home/{{ ansible_user }}/first-devops-project
    docker compose up --build -d
